name: GamingBlockPlug
main: me.jesfot.gamingblockplug.plugin.BukkitPlugin
version: 1.13-1.1.0
description: Plugin for the Gaming Block Server
depends: [uneiConfiguration]
api-version: 1.13
authors: ["JësFot"]
commands:
  role:
    description: Role managing.
    usage: |
            /<command> list -- List roles.
            /<command> add|remove <role> -- Add or remove roles.
            /<command> option <role> <option> [value] -- Get or modify role options.
            /<command> set <player> <role> -- Set a role to a player.
            /<command> reset <player> -- Reset a player role to default.
    aliases: [gbprole, roles]
  ping:
    description: Ping ! Pong !
    usage: /<command>
    aliases: [gbpping]
  spawn:
    description: Teleport yourself at the world spawn
    usage: |
            /<command> [set [<x> <y> <z> [<pitch> <yaw>]]]
            /<command> remove [<world>]
    aliases: [gbpspawn, home, spa]
  warp:
    description: Teleport someone to a registered point
    usage: /<command> [name [player]] -- List warps or teleport someone
    aliases: [gbpwarp, tpto, warps]
  setwarp:
    description: Setup a warp point
    usage: |
            /<command> <name> [[<world>] <x> <y> <z> [<pitch> <yaw>]]
            /<command> <name> remove [<world>]
    aliases: [gbpsetwarp, unsetwarp, warpctrl]
  logmsg:
    description: Print or setup a login message.
    usage: /<command> [set <message...>]
    aliases: [gbplogmsg, motd, lm]
  spectate:
    description: Change from survival to spectator mode.
    usage: /<command>
    aliases: [gbpspectate, spec, noclip]
  fly:
    description: Enable or disable flying mode.
    usage: |
            /<command> [on/off]
            /<command> <player> on/off
    aliases: [gbpfly]
  forcepassnight:
    description: Enable only one player in bed.
    usage: /<command>
    aliases: [gbpforcepassnight, passnight, fpn]
  spychest:
    description: Open someone's inventory
    usage: /<command> <player> [normal/ender]
    aliases: [gbpspychest]
  var:
    description: Variables management.
    usage: |
            /<command> <name>
            /<command> unset <name>
            /<command> set <name> <type> <value...>
            /<command> help all/<rubric>
    aliases: [gbpvar, variable, variables, vars]
  toolb:
    description: Get a dead bush item, used for shared chest.
    usage: /<command>
    aliases: [gbptoolb, deadbush, commonchest]