name: MetalPonyPlug
main: fr.mpp.bukkit.BukkitPlugin
version: 5.4
description: Plugin for PonyMetalCraft server
authors: ["JesFot"]
permissions:
  mpp.mpp.*:
    description: All mpp commands
    children:
      mpp.mpp.testmpp: true
      mpp.mpp.forall: true
  mpp.mpp.testmpp:
    description: Mpp testing command
    default: true
  mpp.mpp.forall:
    description: Home and Tpa
    default: true
  mpp.setconf:
    description: Config of mpp
    default: false
  mpp.info: #/plugins, version, help, list and others desillusions
    description: Base commands
    default: true
  mpp.admin.*:
    description: Admin commands
    children:
      mpp.admin.base: true
      mpp.admin.advence: true
  mpp.admin.base:
    description: Basic admin commands
    default: false
  mpp.admin.advence:
    description: Advenced admin commands
    default: false
commands:
  testmpp:
    com: testmpp
    description: Commande test.
    usage: /<command> [word]
  #mpp:
    #com: mpp
    #description: MetalPonyPlug configuration
    #usage: /<command> <reset|set> [all]
  mpp-off:
    description: Do Not Use IT
    usage: /<command>
  mhome:
    description: Set or teleport you at home, sweet home :p
    usage: /<command> [set]
  mppsetchest:
    description: Set the chest
    usage: /<command>
  mtpa:
    description: Tpa
    usage: /<command> [player] <target>
  election:
    description: Make an election
    usage: /<command> <start>, /<command> <set> <type>
    aliases: [maire, elecmaire]
