name: MetalPonyPlug
main: fr.mpp.bukkit.BukkitPlugin
version: 6.3.6
description: Plugin for PonyMetalCraft server
authors: ["JesFot"]
commands:
  testmpp:
    com: testmpp
    description: Commande test.
    usage: /<command> [word]
  mpp-off:
    description: Do Not Use IT
    permission: op
    usage: /<command>
  mhome:
    description: Set or teleport you at a home, sweet home :p
    usage: /<command> [homeName] [set]
    aliases: [home, h]
  mtpa:
    description: Tpa
    usage: /<command> [player] <target>
    aliases: [tpa]
  #election:
    #description: Make an election
    #usage: /<command> <start>, /<command> <set> <type>
    #aliases: [maire, elecmaire]
  economy:
    description: See your money or pay someone
    usage: /<command> [pay <player> <money>]
    aliases: [eco]
  logmessage:
    description: Show or set the login message
    usage: /<command> [set <text...>]
    aliases: [logmsg, lmessage]
  seed:
    description: Shows the world seed
    usage: /<command>
  language:
    description: change system language
    usage: /<command> <Language_name>
    aliases: [lang]
  world:
    description: world changer method
    usage: /<command> ...
    aliases : [worlds]
  var:
    description: Set or see variables
    usage: /<command> <valueName> or /<command> set <valueName> <type> <value>
  mtpc:
    description: Teleports the given player (or yourself) to coordinates
    usage: /<command> [player] <x> <y> <z>
#  opencity:
#    description: Open a door of a city
#    usage: /<command> <doorID> [open|close]
#    aliases: [ouvrir]