name: MetalPonyPlug_on
main: fr.mppon.bukkit.BukkitPlugin
version: 1.0
description: Plugin for PonyMetalCraft server
authors: ["JesFot"]
commands:
  mpp-on:
    description: Do Not Use IT
    usage: /<command>
