mpp_null: false
mpp:
  aff:
    rank:
      jesfot:
        str: affich
        id: 3
      lydia_drew:
        str: statut
        id: 3
      polm:
        str: main
        id: 0
      overmind:
        str: mask
        id: 5
salary:
  daily: 5.0
  mensual: 1.0
economy:
  basemoney: 100.0
  jesfot:
    money: 100.0