name: GamingBlockPlug
main: fr.gbp.bukkit.BukkitPlugin
version: 1.4 BETA PRE
description: Plugin for Gaming Block Server
authors: ["JesFot"]
commands:
  testgbp:
    description: Commande test.
    usage: /<command> [word]
  gtpa:
    description: Same as tpa in essentials
    usage: /<command> <targetPlayer>
    aliases: [tpa]
  ghome:
    description: Same as home in essentials
    usage: /<command> [set] | /<command> <locName> [set]
    aliases: [home, h]
  gtpc:
    description: Teleportation to coordinates
    usage: /<command> [player] <x> <y> <z>
    aliases: [tpc]
  giveperm:
    description: manage permissions
    usage: /<command> [player] <[-]permission>
  greload:
    description: Reload the plugins
    usage: /<command> [time]
  toolb:
    description: toolb
    usage: /<command>
  economy:
    description: Manage your economy
    usage: /<command> [pay <player> <amount>] | /<command> inventory
    aliases: [eco, ecmy]
  world:
    description: Navigate between worlds.
    usage: /<command> list | /<command> tp <worldName> | /<command> set <worldName> <load|unload> [newSeed] [Env] [Type]
  gmask:
    description: allows you to make yourself invisible
    usage: /<command>
    aliases: [mask, vanish, offline]