name: GamingBlocksPlug
main: fr.gbp.bukkit.BukkitPlugin
version: 2.5 BETA
description: Plugin for GamingBlocks server
authors: ["JesFot"]
commands:
  testgbp:
    com: testgbp
    description: Commande test.
    usage: /<command> [word]
  addme:
    description: Add you to the economy system
    usage: /<command>
