name: GamingBlocksPlug
main: fr.gbp.bukkit.BukkitPlugin
version: 4.2
description: Plugin for GamingBlocks server
authors: ["JesFot"]
commands:
  testgbp:
    com: testgbp
    description: Commande test.
    usage: /<command> [word]
  addme:
    description: Add you to the economy system
    usage: /<command>
  acount:
    description: Manage your acount !
    usage: /<command> <reset>
  toolb:
    description: Give you the bank acces tool
    usage: /<command>
  gtpa:
    description: Same as /tpa in Essentials
    usage: /<command> <player>
  bank:
    description: Bank user management command
    usage: /<command> <pay> <Player> <amount>
  pay:
    description: Pay someone.
    usage: /<command> <Player> <amount>
