name: GamingBlocksPlug
main: fr.gbp.bukkit.BukkitPlugin
version: 1.0 ALPHA
description: Plugin for GamingBlocks server
authors: ["JesFot"]
commands:
  testmpp:
    com: testgbp
    description: Commande test.
    usage: /<command> [word]
