name: EliryumPlug
main: me.emp.bukkit.BukkitPlugin
version: 1.2.4
description: Plugin made for the Eliryum server
authors: ["JesFot"]
commands:
  switch:
    description: Enable or disable plugin
    #permission: Eliryum.switch
    usage: /<command> <pluginName> <on|off>
  var:
    description: Variables command
    usage: /<command> <varName> or /<command> set <varName> <type> <value> or /<command> unset <varName>
  mask:
    description: Make you vanished for other players
    usage: /<command>
    aliases: [vanish, disepear, flogout]